

class AsmaUlHusnaData {
  static const List<Map<String, String>> data = [
    {"number": "1", "arabic": "ٱلْرَّحْمَـانُ", "transliteration": "AR-RAHMAAN", "meaning": "The Most or Entirely Merciful"},
    {"number": "2", "arabic": "ٱلْرَّحِيْمُ", "transliteration": "AR-RAHEEM", "meaning": "The Bestower of Mercy"},
    {"number": "3", "arabic": "ٱلْمَلِكُ", "transliteration": "AL-MALIK", "meaning": "The King and Owner of Dominion"},
    {"number": "4", "arabic": "ٱلْقُدُّوسُ", "transliteration": "AL-QUDDUS", "meaning": "The Absolutely Pure"},
    {"number": "5", "arabic": "ٱلْسَّلَامُ", "transliteration": "AS-SALAM", "meaning": "The Perfection and Giver of Peace"},
    {"number": "6", "arabic": "ٱلْمُؤْمِنُ", "transliteration": "AL-MU’MIN", "meaning": "The One Who gives Emaan and Security"},
    {"number": "7", "arabic": "ٱلْمُهَيْمِنُ", "transliteration": "AL-MUHAYMIN", "meaning": "The Guardian, The Witness, The Overseer"},
    {"number": "8", "arabic": "ٱلْعَزِيزُ", "transliteration": "AL-AZEEZ", "meaning": "The All Mighty"},
    {"number": "9", "arabic": "ٱلْجَبَّارُ", "transliteration": "AL-JABBAR", "meaning": "The Compeller, The Restorer"},
    {"number": "10", "arabic": "ٱلْمُتَكَبِّرُ", "transliteration": "AL-MUTAKABBIR", "meaning": "The Supreme, The Majestic"},
    {"number": "11", "arabic": "ٱلْخَالِقُ", "transliteration": "AL-KHAALIQ", "meaning": "The Creator, The Maker"},
    {"number": "12", "arabic": "ٱلْبَارِئُ", "transliteration": "AL-BAARI’", "meaning": "The Originator"},
    {"number": "13", "arabic": "ٱلْمُصَوِّرُ", "transliteration": "AL-MUSAWWIR", "meaning": "The Fashioner"},
    {"number": "14", "arabic": "ٱلْغَفَّارُ", "transliteration": "AL-GHAFFAR", "meaning": "The All- and Oft-Forgiving"},
    {"number": "15", "arabic": "ٱلْقَهَّارُ", "transliteration": "AL-QAHHAR", "meaning": "The Subduer, The Ever-Dominating"},
    {"number": "16", "arabic": "ٱلْوَهَّابُ", "transliteration": "AL-WAHHAAB", "meaning": "The Giver of Gifts"},
    {"number": "17", "arabic": "ٱلْرَّزَّاقُ", "transliteration": "AR-RAZZAAQ", "meaning": "The Provider"},
    {"number": "18", "arabic": "ٱلْفَتَّاحُ", "transliteration": "AL-FATTAAH", "meaning": "The Opener, The Judge"},
    {"number": "19", "arabic": "ٱلْعَلِيمُ", "transliteration": "AL-‘ALEEM", "meaning": "The All-Knowing, The Omniscient"},
    {"number": "20", "arabic": "ٱلْقَابِضُ", "transliteration": "AL-QAABID", "meaning": "The Withholder"},
    {"number": "21", "arabic": "ٱلْبَاسِطُ", "transliteration": "AL-BAASIT", "meaning": "The Extender"},
    {"number": "22", "arabic": "ٱلْخَافِضُ", "transliteration": "AL-KHAAFIDH", "meaning": "The Reducer, The Abaser"},
    {"number": "23", "arabic": "ٱلْرَّافِعُ", "transliteration": "AR-RAAFI’", "meaning": "The Exalter, The Elevator"},
    {"number": "24", "arabic": "ٱلْمُعِزُّ", "transliteration": "AL-MU’IZZ", "meaning": "The Honourer, The Bestower"},
    {"number": "25", "arabic": "ٱلْمُذِلُّ", "transliteration": "AL-MUZIL", "meaning": "The Dishonourer, The Humiliator"},
    {"number": "26", "arabic": "ٱلْسَّمِيعُ", "transliteration": "AS-SAMEE’", "meaning": "The All-Hearing"},
    {"number": "27", "arabic": "ٱلْبَصِيرُ", "transliteration": "AL-BASEER", "meaning": "The All-Seeing"},
    {"number": "28", "arabic": "ٱلْحَكَمُ", "transliteration": "AL-HAKAM", "meaning": "The Judge, The Giver of Justice"},
    {"number": "29", "arabic": "ٱلْعَدْلُ", "transliteration": "AL-‘ADL", "meaning": "The Utterly Just"},
    {"number": "30", "arabic": "ٱلْلَّطِيفُ", "transliteration": "AL-LATEEF", "meaning": "The Subtle One, The Most Gentle"},
    {"number": "31", "arabic": "ٱلْخَبِيرُ", "transliteration": "AL-KHABEER", "meaning": "The Acquainted, the All-Aware"},
    {"number": "32", "arabic": "ٱلْحَلِيمُ", "transliteration": "AL-HALEEM", "meaning": "The Most Forbearing"},
    {"number": "33", "arabic": "ٱلْعَظِيمُ", "transliteration": "AL-‘ATHEEM", "meaning": "The Magnificent, The Supreme"},
    {"number": "34", "arabic": "ٱلْغَفُورُ", "transliteration": "AL-GHAFOOR", "meaning": "The Forgiving, The Exceedingly Forgiving"},
    {"number": "35", "arabic": "ٱلْشَّكُورُ", "transliteration": "ASH-SHAKOOR", "meaning": "The Most Appreciative"},
    {"number": "36", "arabic": "ٱلْعَلِيُّ", "transliteration": "AL-‘ALEE", "meaning": "The Most High, The Exalted"},
    {"number": "37", "arabic": "ٱلْكَبِيرُ", "transliteration": "AL-KABEER", "meaning": "The Greatest, The Most Grand"},
    {"number": "38", "arabic": "ٱلْحَفِيظُ", "transliteration": "AL-HAFEEDH", "meaning": "The Preserver, The All-Heedful and All-Protecting"},
    {"number": "39", "arabic": "ٱلْمُقِيتُ", "transliteration": "AL-MUQEET", "meaning": "The Sustainer"},
    {"number": "40", "arabic": "ٱلْحَسِيبُ", "transliteration": "AL-HASEEB", "meaning": "The Reckoner, The Sufficient"},
    {"number": "41", "arabic": "ٱلْجَلِيلُ", "transliteration": "AL-JALEEL", "meaning": "The Majestic"},
    {"number": "42", "arabic": "ٱلْكَرِيمُ", "transliteration": "AL-KAREEM", "meaning": "The Most Generous, The Esteemed"},
    {"number": "43", "arabic": "ٱلْرَّقِيبُ", "transliteration": "AR-RAQEEM", "meaning": "The Watchful"},
    {"number": "44", "arabic": "ٱلْمُجِيبُ", "transliteration": "AL-MUJEEB", "meaning": "The Responsive One"},
    {"number": "45", "arabic": "ٱلْوَاسِعُ", "transliteration": "AL-WAASI’", "meaning": "The All-Encompassing, The Boundless"},
    {"number": "46", "arabic": "ٱلْحَكِيمُ", "transliteration": "AL-HAKEEM", "meaning": "The All-Wise"},
    {"number": "47", "arabic": "ٱلْوَدُودُ", "transliteration": "AL-WADUD", "meaning": "The Loving One"},
    {"number": "48", "arabic": "ٱلْمَجِيدُ", "transliteration": "AL-MAJEED", "meaning": "The Illustrious, The Honorable"},
    {"number": "49", "arabic": "ٱلْبَاعِثُ", "transliteration": "AL-BA’ITH", "meaning": "The Infuser of New Life"},
    {"number": "50", "arabic": "ٱلْشَّهِيدُ", "transliteration": "ASH-SHAHEED", "meaning": "The All Observing Witness"},
    {"number": "51", "arabic": "ٱلْحَقُ", "transliteration": "AL-HAQQ", "meaning": "The Absolute Truth"},
    {"number": "52", "arabic": "ٱلْوَكِيلُ", "transliteration": "AL-WAKEEL", "meaning": "The Trustee, The Disposer of Affairs"},
    {"number": "53", "arabic": "ٱلْقَوِيُّ", "transliteration": "AL-QAWIYY", "meaning": "The All-Strong"},
    {"number": "54", "arabic": "ٱلْمَتِينُ", "transliteration": "AL-MATEEN", "meaning": "The Firm, The Steadfast"},
{"number": "55", "arabic": "ٱلْوَلِيُّ", "transliteration": "AL-WALIYY", "meaning": "The Protecting Associate"},
{"number": "56", "arabic": "ٱلْحَمِيدُ", "transliteration": "AL-HAMEED", "meaning": "The Praiseworthy"},
{"number": "57", "arabic": "ٱلْمُحْصِيُ", "transliteration": "AL-MUHSEE", "meaning": "The All-Enumerating, The Counter"},
{"number": "58", "arabic": "ٱلْمُبْدِئُ", "transliteration": "AL-MUBDI", "meaning": "The Originator, The Initiator"},
{"number": "59", "arabic": "ٱلْمُعِيدُ", "transliteration": "AL-MU’ID", "meaning": "The Restorer, The Reinstater"},
{"number": "60", "arabic": "ٱلْمُحْيِى", "transliteration": "AL-MUHYEE", "meaning": "The Giver of Life"},
{"number": "61", "arabic": "ٱلْمُمِيتُ", "transliteration": "AL-MUMEET", "meaning": "The Bringer of Death, the Destroyer"},
{"number": "62", "arabic": "ٱلْحَىُّ", "transliteration": "AL-HAYY", "meaning": "The Ever-Living"},
{"number": "63", "arabic": "ٱلْقَيُّومُ", "transliteration": "AL-QAYYOOM", "meaning": "The Sustainer, The Self-Subsisting"},
{"number": "64", "arabic": "ٱلْوَاجِدُ", "transliteration": "AL-WAAJID", "meaning": "The Perceiver"},
{"number": "65", "arabic": "ٱلْمَاجِدُ", "transliteration": "AL-MAAJID", "meaning": "The Illustrious, the Magnificent"},
{"number": "66", "arabic": "ٱلْوَاحِدُ", "transliteration": "AL-WAAHID", "meaning": "The One"},
{"number": "67", "arabic": "ٱلْأَحَد", "transliteration": "AL-AHAD", "meaning": "The Unique, The Only One"},
{"number": "68", "arabic": "ٱلْصَّمَدُ", "transliteration": "AS-SAMAD", "meaning": "The Eternal, Satisfier of Needs"},
{"number": "69", "arabic": "ٱلْقَادِرُ", "transliteration": "AL-QADIR", "meaning": "The Capable, The Powerful"},
{"number": "70", "arabic": "ٱلْمُقْتَدِرُ", "transliteration": "AL-MUQTADIR", "meaning": "The Omnipotent"},
{"number": "71", "arabic": "ٱلْمُقَدِّمُ", "transliteration": "AL-MUQADDIM", "meaning": "The Expediter, The Promoter"},
{"number": "72", "arabic": "ٱلْمُؤَخِّرُ", "transliteration": "AL-MU’AKHKHIR", "meaning": "The Delayer, the Retarder"},
{"number": "73", "arabic": "ٱلأَوَّلُ", "transliteration": "AL-AWWAL", "meaning": "The First"},
{"number": "74", "arabic": "ٱلْآخِرُ", "transliteration": "AL-AAKHIR", "meaning": "The Last"},
{"number": "75", "arabic": "ٱلْظَّاهِرُ", "transliteration": "AZ-DHAAHIR", "meaning": "The Manifest"},
{"number": "76", "arabic": "ٱلْبَاطِنُ", "transliteration": "AL-BAATIN", "meaning": "The Hidden One, Knower of the Hidden"},
{"number": "77", "arabic": "ٱلْوَالِي", "transliteration": "AL-WAALI", "meaning": "The Governor, The Patron"},
{"number": "78", "arabic": "ٱلْمُتَعَالِي", "transliteration": "AL-MUTA’ALI", "meaning": "The Self Exalted"},
{"number": "79", "arabic": "ٱلْبَرُّ", "transliteration": "AL-BARR", "meaning": "The Source of Goodness, the Kind Benefactor"},
{"number": "80", "arabic": "ٱلْتَّوَّابُ", "transliteration": "AT-TAWWAB", "meaning": "The Ever-Pardoning, The Relenting"},
{"number": "81", "arabic": "ٱلْمُنْتَقِمُ", "transliteration": "AL-MUNTAQIM", "meaning": "The Avenger"},
{"number": "82", "arabic": "ٱلْعَفُوُّ", "transliteration": "AL-‘AFUWW", "meaning": "The Pardoner"},
{"number": "83", "arabic": "ٱلْرَّؤُفُ", "transliteration": "AR-RA’OOF", "meaning": "The Most Kind"},
{"number": "84", "arabic": "مَالِكُ ٱلْمُلْكُ", "transliteration": "MAALIK-UL-MULK", "meaning": "Master of the Kingdom, Owner of the Dominion"},
{"number": "85", "arabic": "ذُو ٱلْجَلَالِ وَٱلْإِكْرَامُ", "transliteration": "DHUL-JALAALI WAL-IKRAAM", "meaning": "Possessor of Glory and Honour, Lord of Majesty and Generosity"},
{"number": "86", "arabic": "ٱلْمُقْسِطُ", "transliteration": "AL-MUQSIT", "meaning": "The Equitable, the Requiter"},
{"number": "87", "arabic": "ٱلْجَامِعُ", "transliteration": "AL-JAAMI’", "meaning": "The Gatherer, the Uniter"},
{"number": "88", "arabic": "ٱلْغَنيُّ", "transliteration": "AL-GHANIYY", "meaning": "The Self-Sufficient, The Wealthy"},
{"number": "89", "arabic": "ٱلْمُغْنِيُّ", "transliteration": "AL-MUGHNI", "meaning": "The Enricher"},
{"number": "90", "arabic": "ٱلْمَانِعُ", "transliteration": "AL-MANI’", "meaning": "The Withholder"},
{"number": "91", "arabic": "ٱلْضَّارُ", "transliteration": "AD-DHARR", "meaning": "The Distresser"},
{"number": "92", "arabic": "ٱلْنَّافِعُ", "transliteration": "AN-NAFI’", "meaning": "The Propitious, the Benefactor"},
{"number": "93", "arabic": "ٱلْنُّورُ", "transliteration": "AN-NUR", "meaning": "The Light, The Illuminator"},
{"number": "94", "arabic": "ٱلْهَادِي", "transliteration": "AL-HAADI", "meaning": "The Guide"},
{"number": "95", "arabic": "ٱلْبَدِيعُ", "transliteration": "AL-BADEE’", "meaning": "The Incomparable Originator"},
{"number": "96", "arabic": "ٱلْبَاقِي", "transliteration": "AL-BAAQI", "meaning": "The Ever-Surviving, The Everlasting"},
{"number": "97", "arabic": "ٱلْوَارِثُ", "transliteration": "AL-WAARITH", "meaning": "The Inheritor, The Heir"},
{"number": "98", "arabic": "ٱلْرَّشِيدُ", "transliteration": "AR-RASHEED", "meaning": "The Guide, Infallible Teacher"},
{"number": "99", "arabic": "ٱلْصَّبُورُ", "transliteration": "AS-SABOOR", "meaning": "The Forbearing, The Patient"}
];
}
