name: maarifa
description: "Uniting hearts through Quran and Sunnah"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  form_validator: ^2.1.1
  go_router: ^14.2.3
  flutter_svg: ^2.0.10+1
  http: ^1.2.2
  image_picker: ^1.1.2
  path_provider: ^2.1.4  # might not need depending on user profiles
  permission_handler: ^11.3.1  # might not need depending on user prfoiles
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_fonts: ^6.2.1
  audioplayers: ^6.1.0
  hadith: ^1.0.0
  html: ^0.15.4
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.2
  firebase_storage: ^12.3.1
  connectivity_plus: ^6.0.5
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  intl: ^0.19.0
  dio: ^5.7.0
  path: ^1.9.0
  shared_preferences: ^2.3.2
  flutter_local_notifications: ^17.2.3
  firebase_messaging: ^15.1.3
  pdfx: ^2.8.0
  saver_gallery: ^4.0.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.12


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/cards/
     - assets/audio/99_Names_of_Allah.mp3
     - assets/images/placeholder.jpeg
     - assets/images/books/Explanation of the Four Fundamental Principles.jpg
     - assets/images/books/Explanation of the Three fundamental Principles of islam.jpg
     - assets/images/books/Explanation of the Nullifiers of Islam.jpg
     - assets/images/books/Forbidden Matters Taken Lightly by Some People.jpg
     - assets/images/books/Ibn Qayyim on Knowledge.jpg
     - assets/images/books/Forty Hadith al Nawawi.jpg
     - assets/images/books/Kashfush Shubuhaat.jpg
     - assets/images/books/Kitab Al Tawheed.jpg
     - assets/images/books/Knowledge Mandates Action.jpg
     - assets/images/books/Man Made Laws Vs Shariah.jpg
     - assets/images/books/Manners of the Knowledge Seeker.jpg
     - assets/images/books/Minhaj al Muslim Vol1.jpg
     - assets/images/books/Minhaj al Muslim Vol2.jpg
     - assets/images/books/Selections from the Fath al Bari.jpg
     - assets/images/books/Tafseer Katheer.jpg
     - assets/images/books/Tafseer Saadi.jpg
     - assets/images/books/The Sealed Nectar.jpg
     - assets/images/books/The Excellence Of Knowledge.jpg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Poppins
       fonts:
         - asset: assets/Poppins-Light.ttf
           style: normal
     - family: PoppinsBold
       fonts:
         - asset: assets/Poppins-Bold.ttf
           style: normal
     - family: PoppinsItalic
       fonts:
         - asset: assets/Poppins-LightItalic.ttf
           style: normal
     - family: Roboto
       fonts:
         - asset: assets/RobotoMono-Light.ttf
           weight: 700
     - family: AmiriRegular
       fonts:
         - asset: assets/AmiriQuran-Regular.ttf
           style: normal
     - family: AmiriRegularNormal
       fonts:
         - asset: assets/Amiri-Regular.ttf
           style: normal
     - family: Kaleem
       fonts:
         - asset: assets/KaleemRegular.otf
           style: normal
     - family: Bismillah
       fonts:
         - asset: assets/arabic.ttf
           style: normal
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
